baseURL = "https://docs.droidian.org/"
languageCode = "en-us"
title = "Droidian"
theme = "gohugo-theme-ananke"

[params]
  custom_css = ["css/theme.css", "css/custom.css", "css/fork-awesome.min.css"]
  env = "production"

[markup.goldmark.renderer]
  unsafe = true

# Controls the navigation
[[menu.main]]
  identifier = "home"
  name = "Home"
  title = "home"
  url = "/"
  weight = -400

[[menu.main]]
  identifier = "install"
  name = "Installation"
  title = "Installation docs"
  url = "/install"
  weight = -340

[[menu.main]]
  identifier = "faq"
  name = "FAQ"
  title = "Frequently asked questions"
  url = "/faq"
  weight = -340

[[menu.main]]
  identifier = "info"
  name = "Tips and Tricks"
  title = "Useful info and workarounds"
  url = "/info"
  weight = -340

[[menu.main]]
  identifier = "porting-guide"
  name = "Porting guide"
  title = "Porting guide"
  url = "/porting-guide"
  weight = -340

[[menu.main]]
  identifier = "devel"
  name = "Development"
  title = "Droidian platform development"
  url = "/devel"
  weight = -340
